
[godin]
  version = "0.1.1"

[project]
  created = "Wed, 29 May 2019 20:22:14 CEST"

[protobuf]
  package = "yyy/api"
  service = "yyy"

[service]
  module = "yyy"
  name = "yyy"
  namespace = "yyy"

  [endpoints.Hello]
    protoRequest = "HelloRequest"
    protoResponse = "HelloResponse"

  [service.middleware]
    authorization = false
    caching = false
    logging = true
    recovery = true

[grpc]
  enabled = true
